# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/daily.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DailyAmount(object):
    def setupUi(self, DailyAmount):
        DailyAmount.setObjectName("DailyAmount")
        DailyAmount.resize(400, 429)
        DailyAmount.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(DailyAmount)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(DailyAmount)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(DailyAmount)
        QtCore.QMetaObject.connectSlotsByName(DailyAmount)

    def retranslateUi(self, DailyAmount):
        _translate = QtCore.QCoreApplication.translate
        DailyAmount.setWindowTitle(_translate("DailyAmount", "Montant journalier"))
