# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/situation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reglement(object):
    def setupUi(self, Reglement):
        Reglement.setObjectName("Reglement")
        Reglement.resize(290, 175)
        Reglement.setMaximumSize(QtCore.QSize(290, 175))
        self.verticalLayout = QtWidgets.QVBoxLayout(Reglement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dettesLabel = QtWidgets.QLabel(Reglement)
        self.dettesLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.dettesLabel.setObjectName("dettesLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dettesLabel)
        self.dettesDoubleSpinBox = QtWidgets.QDoubleSpinBox(Reglement)
        self.dettesDoubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.dettesDoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.dettesDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dettesDoubleSpinBox.setMaximum(1e+18)
        self.dettesDoubleSpinBox.setObjectName("dettesDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dettesDoubleSpinBox)
        self.verssemntLabel = QtWidgets.QLabel(Reglement)
        self.verssemntLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.verssemntLabel.setObjectName("verssemntLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.verssemntLabel)
        self.verssemntDoubleSpinBox = QtWidgets.QDoubleSpinBox(Reglement)
        self.verssemntDoubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.verssemntDoubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.verssemntDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.verssemntDoubleSpinBox.setMaximum(1e+18)
        self.verssemntDoubleSpinBox.setObjectName("verssemntDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.verssemntDoubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Reglement)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/src/main/resources/base/img/icons8_coins_50px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Reglement)
        QtCore.QMetaObject.connectSlotsByName(Reglement)

    def retranslateUi(self, Reglement):
        _translate = QtCore.QCoreApplication.translate
        Reglement.setWindowTitle(_translate("Reglement", "Reglement"))
        self.dettesLabel.setText(_translate("Reglement", "Dettes"))
        self.verssemntLabel.setText(_translate("Reglement", "Verssemnt"))
        self.pushButton.setText(_translate("Reglement", "  Regler"))
import img_rc
